server_params:
  host: localhost
  port: 8080

data:
  users_count: 100
  start_timestamp: 1609448400
  names:
    - Daniel
    - Igor
    - Toma
    - Maria
    - Luka
    - Tony
    - Dima
    - Vera
    - Alina
    - Kseniya
    - Mike
    - Pukhlik
    - Scrooge
    - Marina
    - Vasiliy
  cities:
    - Moscow
    - St. Petersburg
    - London
    - Paris
    - New York
    - Kiev
    - Minsk
    - Limassol
    - Prague
    - Beijing
    - Berlin
    - Ivanovsk
  actions:
    - click
    - purchase
    - cart
    - favourite
